name: 构建和部署

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: '部署环境'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: https://gitea.com/actions/checkout@v4

      - name: 设置 Node.js
        uses: https://gitea.com/actions/setup-node@v4
        with:
          node-version: '24'

      - name: 安装 pnpm
        run: corepack enable pnpm

      - name: 安装依赖
        run: |
          cd frontend
          export NODE_NO_WARNINGS=1
          pnpm install --frozen-lockfile

      - name: 验证 API 连接
        run: |
          cd frontend
          export NEXT_PB_URL="${{ vars.NEXT_PB_URL }}"
          export NEXT_PB_AUTH="${{ secrets.NEXT_PB_AUTH }}"
          echo "🔍 验证 API 连接: $NEXT_PB_URL"
          
          # 测试 API 连接（带认证）
          if [ -n "$NEXT_PB_AUTH" ]; then
            AUTH_USER=$(echo $NEXT_PB_AUTH | cut -d: -f1)
            AUTH_PASS=$(echo $NEXT_PB_AUTH | cut -d: -f2)
            if curl -f -s -u "$AUTH_USER:$AUTH_PASS" "$NEXT_PB_URL/api/collections/courses/records" > /dev/null; then
              echo "✅ API 连接正常（带认证）"
            else
              echo "❌ API 连接失败，但继续构建"
            fi
          else
            echo "⚠️ 未设置认证信息，尝试无认证连接"
            if curl -f -s "$NEXT_PB_URL/api/collections/courses/records" > /dev/null; then
              echo "✅ API 连接正常（无认证）"
            else
              echo "❌ API 连接失败，但继续构建"
            fi
          fi

      - name: 构建项目
        run: |
          cd frontend
          export NODE_ENV=production
          export NODE_NO_WARNINGS=1
          export NEXT_PB_URL="${{ vars.NEXT_PB_URL }}"
          export NEXT_PB_AUTH="${{ vars.NEXT_PB_AUTH }}"
          
          echo "🚀 开始构建..."
          echo "NEXT_PB_URL: $NEXT_PB_URL"
          echo "NEXT_PB_AUTH: ${NEXT_PB_AUTH:0:10}..." # 只显示前10个字符
          
          pnpm build
          
          echo "📊 检查生成的路由..."
          if [ -f ".next/standalone/.next/prerender-manifest.json" ]; then
            echo "✅ prerender-manifest.json 存在"
            
            # 显示预生成的路由数量
            COURSE_ROUTES=$(cat .next/standalone/.next/prerender-manifest.json | grep -o '"/course/[^"]*"' | grep -v '/lesson' | wc -l)
            LESSON_ROUTES=$(cat .next/standalone/.next/prerender-manifest.json | grep -o '"/course/[^"]*/lesson[^"]*"' | wc -l)
            QA_ROUTES=$(cat .next/standalone/.next/prerender-manifest.json | grep -o '"/qa/[^"]*"' | grep -v '/lesson' | wc -l)
            QA_LESSON_ROUTES=$(cat .next/standalone/.next/prerender-manifest.json | grep -o '"/qa/[^"]*/lesson[^"]*"' | wc -l)
            
            echo "📈 预生成课程路由数量: $COURSE_ROUTES"
            echo "📈 预生成课时路由数量: $LESSON_ROUTES"
            echo "📈 预生成QA路由数量: $QA_ROUTES"
            echo "📈 预生成QA课时路由数量: $QA_LESSON_ROUTES"
            
            # 检查是否有嵌套路由
            if [ "$LESSON_ROUTES" -gt 0 ]; then
              echo "✅ 嵌套动态路由生成成功"
            else
              echo "❌ 嵌套动态路由生成失败"
            fi
          else
            echo "❌ prerender-manifest.json 不存在"
          fi

      - name: 检查构建产物
        run: |
          cd frontend
          echo "📁 检查构建产物..."
          
          # 检查关键目录
          echo "=== .next/ 目录 ==="
          ls -la .next/ | head -10
          
          echo "=== .next/standalone/ 目录 ==="
          ls -la .next/standalone/ || echo "❌ standalone 目录不存在"
          
          echo "=== .next/static/ 目录 ==="
          ls -la .next/static/ || echo "❌ static 目录不存在"
          
          echo "=== public/ 目录 ==="
          ls -la public/ || echo "❌ public 目录不存在"
          
          # 检查静态资源是否正确复制
          echo "=== 检查静态资源复制 ==="
          if [ -d ".next/standalone/.next/static" ]; then
            echo "✅ 静态资源已复制到 standalone"
            STATIC_SIZE=$(du -sh .next/standalone/.next/static | cut -f1)
            echo "📊 静态资源大小: $STATIC_SIZE"
          else
            echo "❌ 静态资源未复制到 standalone"
          fi
          
          if [ -d ".next/standalone/public" ]; then
            echo "✅ public 目录已复制到 standalone"
            PUBLIC_SIZE=$(du -sh .next/standalone/public | cut -f1)
            echo "📊 public 目录大小: $PUBLIC_SIZE"
          else
            echo "❌ public 目录未复制到 standalone"
          fi

      - name: 上传构建产物到服务器
        uses: https://gitea.com/nanqic/scp-action@v1.0.1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "frontend/.next/standalone,frontend/.next/static,frontend/public"
          target: "/opt/hd-zen-web/"

      - name: 重启服务
        uses: https://gitea.com/nanqic/ssh-action@v1.2.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /opt/hd-zen-web/frontend
            
            echo "🔄 重启服务..."
            
            # 检查服务状态
            if pm2 list | grep -q "hd-zen-web"; then
              echo "📊 当前服务状态:"
              pm2 list | grep hd-zen-web
              
              # 重新加载 PM2 服务（零停机时间）
              pm2 reload hd-zen-web
              echo "✅ 服务重新加载完成"
            else
              echo "🚀 启动新服务..."
              PORT=3011 pm2 start .next/standalone/server.js --name hd-zen-web
              echo "✅ 新服务启动完成"
            fi
            
            # 等待服务启动
            sleep 3
            
            # 验证服务状态
            echo "🔍 验证服务状态..."
            pm2 list | grep hd-zen-web
            
            # 测试服务响应
            echo "🌐 测试服务响应..."
            if curl -f -s http://localhost:3011/ > /dev/null; then
              echo "✅ 服务响应正常"
            else
              echo "❌ 服务响应异常"
            fi
            
            echo "🎉 部署完成！"
