name: 构建和部署

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: '部署环境'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: https://gitea.com/actions/checkout@v4

      - name: 设置 Node.js
        uses: https://gitea.com/actions/setup-node@v4
        with:
          node-version: '24'

      - name: 安装 pnpm
        run: corepack enable pnpm

      - name: 缓存 pnpm 依赖
        uses: https://gitea.com/actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            frontend/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('frontend/package.json') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: 安装依赖
        run: cd frontend && pnpm install --frozen-lockfile

      - name: 构建项目
        run: cd frontend && pnpm build
        env:
          NODE_ENV: production

      - name: 上传构建产物到服务器
        uses: https://gitee.com/actions-mirror/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: |
            frontend/.next/standalone/
            frontend/.next/static/
            frontend/public/
          target: "/opt/hd-zen-web/"

      - name: 重启服务
        uses: https://gitee.com/mirrors_appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /opt/hd-zen-web

            # 重新加载 PM2 服务（零停机时间）
            pm2 reload hd-zen-web || pm2 start .next/standalone/server.js --name hd-zen-web --port 3011

            echo "✅ 部署完成"
