name: 构建和部署

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: '部署环境'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: https://gitea.com/actions/checkout@v4

      - name: 设置 Node.js
        uses: https://gitea.com/actions/setup-node@v4
        with:
          node-version: '24'

      - name: 安装 pnpm
        run: corepack enable pnpm

      - name: 安装依赖
        run: |
          cd frontend
          export NODE_NO_WARNINGS=1
          pnpm install --frozen-lockfile

      - name: 构建项目
        run: |
          cd frontend
          export NODE_ENV=production
          export NODE_NO_WARNINGS=1
          # 从 Gitea actions 变量中读取 NEXT_PB_URL
          export NEXT_PB_URL="${{ vars.NEXT_PB_URL }}"
          pnpm build

      - name: 检查构建产物
        run: |
          echo "=== 执行: ls -la frontend/.next/ ==="
          ls -la frontend/.next/
          echo "=== 执行: ls -la frontend/.next/standalone/ ==="
          ls -la frontend/.next/standalone/ || echo "❌ standalone 目录不存在"
          echo "=== 执行: ls -la frontend/.next/static/ ==="
          ls -la frontend/.next/static/ || echo "❌ static 目录不存在"
          echo "=== 执行: ls -la frontend/public/ ==="
          ls -la frontend/public/ || echo "❌ public 目录不存在"

      - name: 上传构建产物到服务器
        uses: https://gitea.com/nanqic/scp-action@v1.0.1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "frontend/.next/standalone,frontend/.next/static,frontend/public"
          target: "/opt/hd-zen-web/"

      - name: 重启服务
        uses: https://gitea.com/nanqic/ssh-action@v1.2.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /opt/hd-zen-web/frontend

            # 重新加载 PM2 服务（零停机时间）
            pm2 reload hd-zen-web || PORT=3011 pm2 start .next/standalone/server.js --name hd-zen-web

            echo "✅ 部署完成"
