name: 构建和部署

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: '部署环境'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: https://gitea.com/actions/checkout@v4

      - name: 设置 Node.js
        uses: https://gitea.com/actions/setup-node@v4
        with:
          node-version: '24'

      - name: 安装 pnpm
        run: corepack enable pnpm

      - name: 安装依赖
        run: |
          cd frontend
          export NODE_NO_WARNINGS=1
          pnpm install --frozen-lockfile

      - name: 验证 API 连接
        run: |
          cd frontend
          export NEXT_PB_URL="${{ vars.NEXT_PB_URL }}"
          export NEXT_PB_AUTH="${{ secrets.NEXT_PB_AUTH }}"  # 认证信息放在 secrets 中更安全
          echo "🔍 验证 API 连接: $NEXT_PB_URL"
          
          # 测试 API 连接（带认证）
          if [ -n "$NEXT_PB_AUTH" ]; then
            AUTH_USER=$(echo $NEXT_PB_AUTH | cut -d: -f1)
            AUTH_PASS=$(echo $NEXT_PB_AUTH | cut -d: -f2)
            if curl -f -s -u "$AUTH_USER:$AUTH_PASS" "$NEXT_PB_URL/api/collections/courses/records" > /dev/null; then
              echo "✅ API 连接正常（带认证）"
            else
              echo "❌ API 连接失败，但继续构建"
            fi
          else
            echo "⚠️ 未设置认证信息，尝试无认证连接"
            if curl -f -s "$NEXT_PB_URL/api/collections/courses/records" > /dev/null; then
              echo "✅ API 连接正常（无认证）"
            else
              echo "❌ API 连接失败，但继续构建"
            fi
          fi

      - name: 构建项目
        run: |
          cd frontend
          export NODE_ENV=production
          export NODE_NO_WARNINGS=1
          export NEXT_PB_URL="${{ vars.NEXT_PB_URL }}"
          export NEXT_PB_AUTH="${{ secrets.NEXT_PB_AUTH }}"  # 认证信息放在 secrets 中更安全
          
          echo "🚀 开始构建..."
          echo "NEXT_PB_URL: $NEXT_PB_URL"
          echo "NEXT_PB_AUTH: ${NEXT_PB_AUTH:0:10}..." # 只显示前10个字符
          
          # 设置构建超时时间（10分钟）
          timeout 600 pnpm build || {
            echo "⚠️ 构建过程出现问题，检查构建产物..."
            # 检查 Next.js 构建是否成功
            if [ -d ".next" ] && [ -f ".next/standalone/server.js" ]; then
              echo "✅ Next.js 构建成功，检查静态资源..."
              
              # 手动复制静态资源（如果构建脚本失败）
              if [ ! -d ".next/standalone/.next/static" ]; then
                echo "📁 手动复制静态资源..."
                mkdir -p .next/standalone/.next/
                cp -r .next/static .next/standalone/.next/ || echo "⚠️ 静态资源复制失败"
              fi
              
              if [ ! -d ".next/standalone/public" ]; then
                echo "📁 手动复制 public 目录..."
                cp -r public .next/standalone/ || echo "⚠️ public 目录复制失败"
              fi
              
              echo "✅ 构建产物检查完成，继续部署"
            else
              echo "❌ Next.js 构建失败，退出"
              exit 1
            fi
          }
          
          # 构建后验证
          echo "🔍 验证构建产物..."
          if [ ! -f ".next/standalone/server.js" ]; then
            echo "❌ standalone server.js 不存在"
            exit 1
          fi
          
          # 自动修复静态资源
          if [ ! -d ".next/standalone/.next/static" ]; then
            echo "📁 复制静态资源..."
            mkdir -p .next/standalone/.next/
            cp -r .next/static .next/standalone/.next/
          fi
          
          if [ ! -d ".next/standalone/public" ]; then
            echo "📁 复制 public 目录..."
            cp -r public .next/standalone/
          fi
          
          echo "✅ 构建验证完成"

      - name: 检查构建产物
        run: |
          cd frontend
          echo "📁 构建产物检查..."
          ls -la .next/standalone/ | head -5
          echo "✅ 构建产物检查完成"

      - name: 上传构建产物到服务器
        uses: https://gitea.com/nanqic/scp-action@v1.0.1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "frontend/.next/standalone,frontend/.next/static,frontend/public"
          target: "/opt/hd-zen-web/"

      - name: 重启服务
        uses: https://gitea.com/nanqic/ssh-action@v1.2.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /opt/hd-zen-web/frontend
            
            echo "🔄 重启服务..."
            
            # 检查服务状态
            if pm2 list | grep -q "hd-zen-web"; then
              echo "📊 当前服务状态:"
              pm2 list | grep hd-zen-web
              
              # 重新加载 PM2 服务（零停机时间）
              pm2 reload hd-zen-web
              echo "✅ 服务重新加载完成"
            else
              echo "🚀 启动新服务..."
              PORT=3011 pm2 start .next/standalone/server.js --name hd-zen-web
              echo "✅ 新服务启动完成"
            fi
            
            # 等待服务启动
            sleep 3
            
            # 验证服务状态
            echo "🔍 验证服务状态..."
            pm2 list | grep hd-zen-web
            
            # 测试服务响应
            echo "🌐 测试服务响应..."
            if curl -f -s http://localhost:3011/ > /dev/null; then
              echo "✅ 服务响应正常"
            else
              echo "❌ 服务响应异常"
            fi
            
            echo "🎉 部署完成！"
