name: 构建和部署

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: '部署环境'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: 安装 pnpm
        run: corepack enable pnpm

      - name: 安装依赖
        run: cd frontend && pnpm install --frozen-lockfile

      - name: 构建项目
        run: cd frontend && pnpm build
        env:
          NODE_ENV: production

      - name: 上传构建产物到服务器
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: |
            frontend/.next/standalone/
            frontend/.next/static/
            frontend/public/
          target: "/opt/hd-zen-web/"

      - name: 重启服务
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /opt/hd-zen-web

            # 重启 PM2 服务
            pm2 restart hd-zen-web || pm2 start .next/standalone/server.js --name hd-zen-web --port 3011

            echo "✅ 部署完成"
